<a href="https://colab.research.google.com/github/adhang/data-science-digital-skola/blob/update/05.%20Numpy%20Array/Homework%20-%20Numpy%20Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework - Numpy Array
Author: Adhang Muntaha Muhammad

[![LinkedIn](https://img.shields.io/badge/linkedin-0077B5?style=for-the-badge&logo=linkedin&logoColor=white&link=https://www.linkedin.com/in/adhangmuntaha/)](https://www.linkedin.com/in/adhangmuntaha/)
[![GitHub](https://img.shields.io/badge/github-121011?style=for-the-badge&logo=github&logoColor=white&link=https://github.com/adhang)](https://github.com/adhang)
[![Kaggle](https://img.shields.io/badge/kaggle-20BEFF?style=for-the-badge&logo=kaggle&logoColor=white&link=https://www.kaggle.com/adhang)](https://www.kaggle.com/adhang)
[![Tableau](https://img.shields.io/badge/tableau-E97627?style=for-the-badge&logo=tableau&logoColor=white&link=https://public.tableau.com/app/profile/adhang)](https://public.tableau.com/app/profile/adhang)
___

## Problems and Tasks

1. Create a 2-dimensional matrix with values like this
2. Create a code to retrieve all red values (values in red cells)
3. Create a code to retrieve all yellow values (values in yellow cells)

<img src='https://drive.google.com/uc?export=view&id=1A-dIyJaDCmGZfSvpGAXW18xQs-cJorkd' width=400>



## Solutions

### Solution - Task 1

In [ ]:
import numpy as np

# first method
# write all data manually
arr = np.array([[1,2,3,4,5,6],
                [7,8,9,10,11,12],
                [13,14,15,16,17,18],
                [19,20,21,22,23,24],
                [25,26,27,28,29,30]])
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
# second method
# since the data is in order, we can use the arange() function
arr = np.array([np.arange(1,6+1),
                np.arange(7,12+1),
                np.arange(13,18+1),
                np.arange(19,24+1),
                np.arange(25,30+1)])
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

### Solution - Task 2
Since the red cells form an L-shape, then (as far as I know) we can't retrieve all values by doiang a single slicing.

In [ ]:
# fetch vertical red numbers
arr_merah_1 = arr[:,1]
arr_merah_1

array([ 2,  8, 14, 20, 26])

In [ ]:
# fetch horizontal red numbers
# number '2' is excluded, so there will be no duplicate data
arr_merah_2 = arr[0,2:]
arr_merah_2

array([3, 4, 5, 6])

### Solution - Task 3

In [ ]:
# fetch yellow numbers
arr_kuning = arr[-2:, -2:]
arr_kuning

array([[23, 24],
       [29, 30]])