<a href="https://colab.research.google.com/github/adhang/data-science-digitalskola/blob/update/05.%20Introduction%20to%20Numpy/Learn%20-%20Introduction%20to%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy
Author: Adhang Muntaha Muhammad

[![LinkedIn](https://img.shields.io/badge/linkedin-0077B5?style=for-the-badge&logo=linkedin&logoColor=white&link=https://www.linkedin.com/in/adhangmuntaha/)](https://www.linkedin.com/in/adhangmuntaha/)
[![GitHub](https://img.shields.io/badge/github-121011?style=for-the-badge&logo=github&logoColor=white&link=https://github.com/adhang)](https://github.com/adhang)
[![Kaggle](https://img.shields.io/badge/kaggle-20BEFF?style=for-the-badge&logo=kaggle&logoColor=white&link=https://www.kaggle.com/adhang)](https://www.kaggle.com/adhang)
[![Tableau](https://img.shields.io/badge/tableau-E97627?style=for-the-badge&logo=tableau&logoColor=white&link=https://public.tableau.com/app/profile/adhang)](https://public.tableau.com/app/profile/adhang)
___
**Contents**
- Creating Array
- Indexing Array
- Reshaping Array
- Joining Array
- Splitting Array
- Sorting Array
- Filtering Array
- Matrix Operation

# Creating Array

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

np.__version__

'1.19.5'

In [ ]:
# 1D array
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [ ]:
# 2D array
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 3D array
arr3 = np.array([
                 [[1,2,3], [4,5,6]], 
                 [[7,8,9], [10,11,12]]
                 ])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# Dimension checking
print("arr1:", arr1.ndim)
print("arr2:", arr2.ndim)
print("arr3:", arr3.ndim)

arr1: 1
arr2: 2
arr3: 3


# Indexing Array

In [ ]:
arr = np.array([i+1 for i in range(20)])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# first element
arr[0]

1

In [ ]:
# last element
arr[-1]

20

In [ ]:
# 6-th element upto last element
arr[5:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# first row
arr2[0]

array([1, 2, 3])

In [ ]:
# first row, 3rd column
arr2[0][2]

3

In [ ]:
# first row, 3rd column
arr2[0, 2]

3

# Reshaping Array

In [ ]:
print("arr:", arr.ndim)
arr

arr: 1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# 4 row, 5 col
arr.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# unspecified size is defined with -1
# 1 col, unkown row (not specified)
arr.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [ ]:
# 5 col, -1 row (20/5 = 4)
arr.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# reshape 1D to 3D
arr.reshape(2,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

# Joining Array

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

concat0 = np.concatenate((arr1, arr2), axis=0)
concat0

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])

concat1 = np.concatenate((arr1, arr2),axis=0)
concat1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
concat2 = np.concatenate((arr1, arr2),axis=1)
concat2

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15]])

# Splitting Array

In [ ]:
print(concat0)
np.array_split(concat0, 2, axis=0)

[1 2 3 4 5 6]


[array([1, 2, 3]), array([4, 5, 6])]

In [ ]:
print(concat1)
np.array_split(concat1, 2, axis=0)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [13 14 15]]


[array([[1, 2, 3],
        [4, 5, 6]]), array([[10, 11, 12],
        [13, 14, 15]])]

In [ ]:
print(concat2)
np.array_split(concat2, 2, axis=1)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]]


[array([[1, 2, 3],
        [4, 5, 6]]), array([[10, 11, 12],
        [13, 14, 15]])]

# Sorting Array

In [ ]:
unsorted_arr = np.array([5,6,2,4,1])
unsorted_arr

array([5, 6, 2, 4, 1])

In [ ]:
# default = ascending
sorted_arr = np.sort(unsorted_arr)
sorted_arr

array([1, 2, 4, 5, 6])

In [ ]:
# descending (wrong)
np.sort(sorted_arr)[:-1]

array([1, 2, 4, 5])

In [ ]:
# descending
np.sort(sorted_arr)[::-1]

array([6, 5, 4, 2, 1])

In [ ]:
# sorting 2D array

arr_2d = np.array([[4,5,1,2], [7,3,9,8]])
arr_2d

array([[4, 5, 1, 2],
       [7, 3, 9, 8]])

In [ ]:
# ascending, sort each row
np.sort(arr_2d)

array([[1, 2, 4, 5],
       [3, 7, 8, 9]])

In [ ]:
# descending (wrong)
np.sort(arr_2d)[::-1]

array([[3, 7, 8, 9],
       [1, 2, 4, 5]])

In [ ]:
# descending, sort each row
np.sort(arr_2d)[::1, ::-1]

array([[5, 4, 2, 1],
       [9, 8, 7, 3]])

# Filtering Array

## Using np.where

In [ ]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.where(arr_2d < 5)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [ ]:
# We can specify the value if the condition is satisfied or not
np.where(arr_2d < 5, True, False)

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [ ]:
# filter data less than 5
arr_2d[np.where(arr_2d < 5)]

array([1, 2, 3, 4])

In [ ]:
# filter data, even number

arr = np.arange(0,20) # like range(start, stop, step)
print(arr)

arr[np.where(arr % 2 == 0)]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Using Mask

In [ ]:
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# see which indices that met the condition
arr % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [ ]:
# array masking
mask = (arr% 2 == 0)
arr[mask]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Matrix Operation
Numpy provides some element-wise matrix operation, such as:
- `add()`
- `subtract()`
- `divide()`
- `multiply()`
If you want to do dot multiplication (not element-wise operation), you can use `dot()`

In [ ]:
# 1D matrix operation

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

np.add(arr1, arr2)

array([5, 7, 9])

In [ ]:
# 2D matrix operation

arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[10,11,12],[13,14,15]])

print('arr3\n', arr3, '\n')
print('arr4\n', arr4, '\n')

print('New arr')
np.add(arr3, arr4)

arr3
 [[1 2 3]
 [4 5 6]] 

arr4
 [[10 11 12]
 [13 14 15]] 

New arr


array([[11, 13, 15],
       [17, 19, 21]])

In [ ]:
# 3D matrix operation

arr5 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr6 = np.array([[[10,11,12],[13,14,15]],[[16,17,18],[19,20,21]]])

print('arr5\n', arr5, '\n')
print('arr6\n', arr6, '\n')

print('New arr')
np.add(arr5, arr6)

arr5
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

arr6
 [[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]] 

New arr


array([[[11, 13, 15],
        [17, 19, 21]],

       [[23, 25, 27],
        [29, 31, 33]]])

In [ ]:
# 2D + 3D matrix operatior
# 2D matrix added to each layer of 3D matrix

arr7 = np.array([[1,2,3],[4,5,6]])
arr8 = np.array([[[10,11,12],[13,14,15]],[[16,17,18],[19,20,21]]])

print('2D arr\n', arr7, '\n')
print('3D arr\n', arr8, '\n')

print('New arr')
np.add(arr7, arr8)

2D arr
 [[1 2 3]
 [4 5 6]] 

3D arr
 [[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]] 

New arr


array([[[11, 13, 15],
        [17, 19, 21]],

       [[17, 19, 21],
        [23, 25, 27]]])