<a href="https://colab.research.google.com/github/adhang/data-science-digitalskola/blob/update/04.%20Introduction%20to%20Numpy/Homework_Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework - Introduction to Numpy
Author: Adhang Muntaha Muhammad

[GitHub](https://github.com/adhang)
[LinkedIn](https://www.linkedin.com/in/adhangmuntaha/)
___

## Soal

1. Buatlah matrix 2 dimensi dengan nilai seperti ini
2. Coding dan ambil angka yang berwarna merah
3. Coding dan ambil angka yang berwarna kuning

<img src='https://drive.google.com/uc?export=view&id=1A-dIyJaDCmGZfSvpGAXW18xQs-cJorkd' width=400>



## Jawaban Soal Nomor 1

In [ ]:
import numpy as np

# cara ke-1
# menuliskan data secara manual
arr = np.array([[1,2,3,4,5,6],
                [7,8,9,10,11,12],
                [13,14,15,16,17,18],
                [19,20,21,22,23,24],
                [25,26,27,28,29,30]])
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
# cara ke-2
# karena datanya urut, bisa menggunakan fungsi arange()
arr = np.array([np.arange(1,6+1),
                np.arange(7,12+1),
                np.arange(13,18+1),
                np.arange(19,24+1),
                np.arange(25,30+1)])
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

## Jawaban Soal Nomor 2
Karena cell berwana merah membentuk L-shape, maka (sepengetahuan saya) tidak bisa dilakukan hanya dengan 1 kali slicing

In [ ]:
# mengambil angka merah vertikal
arr_merah_1 = arr[:,1]
arr_merah_1

array([ 2,  8, 14, 20, 26])

In [ ]:
# mengambil angka merah horizontal
# angka 2 di-exclude, agar tidak terjadi duplicate data
arr_merah_2 = arr[0,2:]
arr_merah_2

array([3, 4, 5, 6])

## Jawaban Soal Nomor 3

In [ ]:
# mengambil angka kuning
arr_kuning = arr[-2:, -2:]
arr_kuning

array([[23, 24],
       [29, 30]])